### ISSUE TITLE
500 Server Error when viewing a Git repo on BitBucket

### ISSUE THREAD

**Issue by exp0nge** [DrkSephy/technetium#1]
For some reason when I subscribe to [this Bitbucket repo](https://bitbucket.org/psuong01/battle-blocks-royale), I get a 500 response when trying to view the reports.

**Comment by DrkSephy** [comment]
Technetium only supports Mercurial-based repositories. You'll have to migrate your `git` repo to `mercurial`. in order to generate reports using Technetium.

**Comment by DrkSephy** [comment]
@exp0nge, I did build a tool a little while ago for working with Git repositories. I'll just have to find the deployment link.

**Comment by exp0nge** [comment]
Are you planning to merge it with this tool?

**Comment by DrkSephy** [comment]
Not anytime in the near future. My tool for Git is built using MongoDB, ExpressJS, AngularJS and NodeJS so it's not directly compatible until I rip out the API functionality for Github and merge it into Technetium.

**Comment by DrkSephy** [comment]
@exp0nge, here is the link to my tool for Git repos: http://git-technetium.herokuapp.com/#/reports. **You'll need to migrate your repository from Bitbucket to Github in order to use it. I recommend this tool here: https://import.github.com/new**. It currently does not support graphs, but it will give you a much more detailed analysis of your repository (with additional options to only view issues, etc). A sample usage and output is shown below:

![git](https://cloud.githubusercontent.com/assets/1226900/10866679/45fa784c-8011-11e5-83e8-491b7d40047d.png)

**Comment by exp0nge** [comment]
Okay, I figured as much when the Bitbucket repos wouldn't work. Still pretty nice but it would have been more useful for it to work on Bitbucket. Thanks.
